### ISSUE TITLE
[plugin-mailq/postfix] bug: Mail queue count `1` reflected as `0` instead

### ISSUE THREAD

**Issue by yongjiajun** [mackerelio/mackerel-agent-plugins#1185]
## Background

When used with Postfix, the `mackerel-plugin-mail` does not correctly reflect the mail queue count value when it is `1`; the value reflected by the plugin is `0`. This is happening because of the following faulty regex expression (at line `31`) used to match the output of the `postqueue -p` command:

https://github.com/mackerelio/mackerel-agent-plugins/blob/92751c4cb3925b828d66a0937cb3b3f93a3c38ea/mackerel-plugin-mailq/lib/main.go#L27-L32

When the mail queue contains only one item, the word `Requests` is singularized as `Request`. 

### Examples
Here's an example output of the `postqueue -p` command when there's only one item:
```
$ postqueue -p
----Queue ID----- --Size-- ---Arrival Time---- --Sender/Recipient------
4Vgbvc4GLXz40kq      11613 Fri May 17 06:02:04 test@example.com
(Host or domain name not found. Name service error for name=localdomain.local type=MX: Host not found, try again)
                                               local@localdomain.local

-- 11 Kbytes in 1 Request.

$ mackerel-plugin-mailq -M postfix
mailq.count     0       1715930097
```

Here's an example output of the `postqueue -p` command when there is more than one item:
```
$ postqueue -p
----Queue ID----- --Size-- ---Arrival Time---- --Sender/Recipient------
4Vgbw31rzhz40tJ      11798 Fri May 17 06:02:27 test@example.com
(Host or domain name not found. Name service error for name=localdomain.local type=MX: Host not found, try again)
                                               local@localdomain.local

4Vgbvc4FYCz40nD      11605 Fri May 17 06:02:04 test@example.com
(Host or domain name not found. Name service error for name=localdomain.local type=MX: Host not found, try again)
                                               local@localdomain.local

-- 22 Kbytes in 2 Requests.

$ mackerel-plugin-mailq -M postfix
mailq.count     2       1715930362
```

## Proposal

This can be easily fixed by updating the faulty regex expression to also match the word `Request` when there's only one item in the mail queue. I'll have a PR for this later.

**Comment by lufia** [comment]
@yongjiajun Sorry for the late reply and thank you for your PR.

We might merge that but please wait for a few hours.
