### ISSUE TITLE
対応するPostgreSQLのバージョンについて

### ISSUE THREAD

**Issue by s-takada** [mackerelio/mackerel-agent-plugins#270]
日本語で失礼します。

こちらのプラグインですが、対応するPostgreSQLのバージョンは何を想定されていますか？
blk_read_time の値を取得する所で、 9.1.4では失敗となった為気付きました。

現行で対応しているバージョンの明記などして頂けると助かります。
また、それ以外のバージョンへの対応予定があれば教えて下さい。

**Comment by a-know** [comment]
I'm sorry, but for users of non Japanese language regions, please use English on GitHub.
I will email you about this issue. Let me close this issue.
