### ISSUE TITLE
Unix Socket support for HAProxy stats site?

### ISSUE THREAD

**Issue by chris-x86-64** [mackerelio/mackerel-agent-plugins#292]
Hi,

haproxy supports sending stats through unix sockets:

> haproxy.cfg
> ```
> stats socket /var/lib/haproxy/stats
> ```

But `mackerel-plugin-haproxy` appears to assume that stats are provided via HTTP.

May I ask for unix socket support for haproxy stats?
Thanks.

**Comment by Songmu** [comment]
Thanks for your feedback.

Of cource, we have a plan to support unix socket. Please wait or you can write patch :)
