### ISSUE TITLE
Please fix Copyright.

### ISSUE THREAD

**Issue by fujiwara** [mackerelio/mackerel-agent-plugins#447]
Hi.

I'm writing a plugin based from this repository.
I need to add original copyrights in my LICENSE file, but the LICENSE in this repository has not a valid copyright.

https://github.com/mackerelio/mackerel-agent-plugins/blob/db03f732fd0f53f3d6fa05fea75dc2d24c5af2d3/LICENSE#L189

**Comment by itchyny** [comment]
@fujiwara Thank you for your report, we fixed a license notice.

**Comment by fujiwara** [comment]
🙏
