### ISSUE TITLE
some plugins can't build

### ISSUE THREAD

**Issue by miwarin** [mackerelio/mackerel-agent-plugins#484]
The following plugin will cause a build error. because these plugins doesn't has "lib" directory.
(these are also not included in the "mackerel-agent-plugins_0.42.0-1_all.deb" package)

```
mackerel-plugin-aws-ec2
mackerel-plugin-aws-kinesis-firehose
mackerel-plugin-aws-rekognition
mackerel-plugin-aws-waf
mackerel-plugin-gcp-compute-engine
mackerel-plugin-gearmand
mackerel-plugin-json
```

in Makefile, plugins must has "lib" directory.

```
$(BINDIR)/mackerel-plugin-%:` mackerel-plugin-%/lib/*.go
```

**Comment by astj** [comment]
Thank you for reporting. Opened #486.
