### ISSUE TITLE
mackerel-plugin-jvm outputs a thread dump to catalina.out on Tomcat every time plugin runs

### ISSUE THREAD

**Issue by azusa** [mackerelio/mackerel-agent-plugins#559]
I had set up a Tomcat Server and enabled `mackerel-plugin-jvm` in `mackerel-agent.conf`.

```
[plugin.metrics.jvm]
command = "mackerel-plugin-jvm -javaname=Bootstrap"
```

## Exptected behavior

JVM process output only application's stdout and mackerel-agent dose not output a application's stdout.

## Actual behavior

JVM process outputs thread dump to stdout(catalina.out) every time mackerel-agens runs(every minute).

catalina.out has grown huge size.

## Environment.

- CentOS Linux release 7.6.1810 (Core)
- openjdk version "1.8.0_212"
- Apache Tomcat Version 9.0.22
- mackerel-agent-0.60.0-1.el7.centos.x86_64
- mackerel-agent-plugins-0.56.0-1.el7.centos.x86_64

**Comment by astj** [comment]
@azusa 
Thank you for reporting.
We've also encountered this issue and are currently investigating.

I'd like to ask you one question.  Your Tomcat Server's behavior and/or performance are not affected by this every-minute thread-dump generation?

**Comment by azusa** [comment]
Our production environment rotates catalina.out by `logrotate` daily.
@astj 

Thanks for your replay.

This is my answer for your question,

>  Your Tomcat Server's behavior and/or performance are not affected by this every-minute thread-dump generation?

Our production environment rotates catalina.out by `logrotate` command daily.

When catalina.out is huge and timing of execution Garbage Collection(GC) and logrotate overlap, it cause delation of GC time, and sometimes it happens OutOfMemoryError and JVM process is down.

**Comment by astj** [comment]
@azusa Thank you for answer! Understand.
And may I ask you which OpenJDK distribution you are using? I guess it's the one provided by CentOS official yum repository, but to ensure.

**Comment by azusa** [comment]
Hi @astj  ,

I found `jinfo` command(with OpenJDK) cannot attach process with user who are not running a application (even `root` user), and output thread dump(s) to stdout.

output is below:

```
[vagrant@localhost src]$ sudo jinfo -flag UseConcMarkSweepGC 13738
13738: Unable to open socket file: target process not responding or HotSpot VM not loaded
```

This is a code for reproduce with `github.com/Songmu/timeout` 

```
package main

import (
        "fmt"
        "github.com/Songmu/timeout"
        "os/exec"
        "time"
        "flag"
)

func main() {

        //arg0 is lvmid
        flag.Parse()

        tio := &timeout.Timeout{
                Cmd:       exec.Command("jinfo", "-flag", "UseConcMarkSweepGC", flag.Arg(0)),
                Duration:  10 * time.Second,
                KillAfter: 5 * time.Second,
        }
        exitStatus, stdout, stderr, err := tio.Run();
        fmt.Print(exitStatus);
        fmt.Print(stdout);
        fmt.Print(stderr);
        if (err != nil){
                fmt.Print(err);
        }
}
```

I'd like that `mackerel-pluin-jvm` has a option to determine a user who runs applition.

**Comment by astj** [comment]
@azusa Thank you for reporting and succeeded to reproduce it.

The situation maybe occurs when "proper user has never requested to open socket before", in other words, "properly-configured mackerel-plugin-jvm is not running against the JVM".
Once the socket is created, unprivileged user's request causes "Operation not permitted" and root can read `jinfo` from the socket, since root can access the socket.
```
$ jinfo -flag UseConcMarkSweepGC 8735
8735: Operation not permitted
$ sudo jinfo -flag UseConcMarkSweepGC 8735
-XX:-UseConcMarkSweepGC
$ sudo -u <OWNER> jinfo -flag UseConcMarkSweepGC 8735
-XX:-UseConcMarkSweepGC
```

Please let me think a bit how to deal with this situation.  (I think user determination is not bad, but there might be other approach... 🤔 )

**Comment by azusa** [comment]
Hi @astj .

> The situation maybe occurs when "proper user has never requested to open socket before", in other words, "properly-configured mackerel-plugin-jvm is not running against the JVM".

I got a result below.

```
[vagrant@localhost ~]$ sudo  jinfo -flag UseConcMarkSweepGC 13255
13255: Unable to open socket file: target process not responding or HotSpot VM not loaded
[vagrant@localhost ~]$ sudo  -u <RUNNER>  jinfo -flag UseConcMarkSweepGC 13255
-XX:-UseConcMarkSweepGC
[vagrant@localhost ~]$ sudo  jinfo -flag UseConcMarkSweepGC 13255
13255: well-known file /tmp/.java_pid13255 is not secure: file should be owned by the current user (which is 0) but is owned by 501
```

IMO,  following this entry,  final output (` well-known file /tmp/.java_pid13255 is not secure`) looks like by design with OpenJDK.

- jcmd が "well-known file is not secure" という IO 例外を上げてくるときの対処 - tokuhirom's blog
http://blog.64p.org/entry/2015/11/04/160605

**Comment by azusa** [comment]
@astj 

Sorry misunderstanding,

I got a result with `sudo -u <RUNNER> mackerel-plugin-jvm` below, and looks fine.

```
[vagrant@localhost ~]$ sudo -u <RUNNER>  mackerel-plugin-jvm  -javaname=Bootstrap
jvm.bootstrap.gc_time_percentage.YGCT   0.000000        1569314177
jvm.bootstrap.gc_time_percentage.FGCT   0.000000        1569314177
jvm.bootstrap.new_space.NGCMX   715784192.000000        1569314177
jvm.bootstrap.new_space.NGC     357957632.000000        1569314177
jvm.bootstrap.new_space.EU      137226035.200000        1569314177
jvm.bootstrap.new_space.S0U     0.000000        1569314177
jvm.bootstrap.new_space.S1U     22447513.600000 1569314177
jvm.bootstrap.old_space.OGCMX   1431699456.000000       1569314177
jvm.bootstrap.old_space.OGC     715849728.000000        1569314177
jvm.bootstrap.old_space.OU      39491686.400000 1569314177
jvm.bootstrap.metaspace.MCMX    1117782016.000000       1569314177
jvm.bootstrap.metaspace.MCMN    0.000000        1569314177
jvm.bootstrap.metaspace.MC      48627712.000000 1569314177
jvm.bootstrap.metaspace.MU      46222643.200000 1569314177
jvm.bootstrap.metaspace.CCSC    6160384.000000  1569314177
jvm.bootstrap.metaspace.CCSU    5531648.000000  1569314177
jvm.bootstrap.memorySpace.oldSpaceRate  5.516757        1569314177
jvm.bootstrap.memorySpace.newSpaceRate  44.606829       1569314177
jvm.bootstrap.gc_events.YGC     0.000000        1569314177
jvm.bootstrap.gc_events.FGC     0.000000        1569314177
jvm.bootstrap.gc_time.YGCT      0.000000        1569314177
jvm.bootstrap.gc_time.FGCT      0.000000        1569314177
```

**Comment by astj** [comment]
@azusa Thank you for quick replies!

> `well-known file /tmp/.java_pid13255 is not secure`

 The behavior is little bit strange, since it's different from that I encountered at https://github.com/mackerelio/mackerel-agent-plugins/issues/559#issuecomment-534437735, but anyway it is not recommended action, as tokuhirom-san's article says. (i.e. `jXXX` commands should be run by the same user as target JVM process.)

> I got a result with `sudo -u <RUNNER> mackerel-plugin-jvm` below, and looks fine.

😄 

From those investigations, I'd like to refer those whole problem as "Please run mackerel-plugin-jvm as the same user as target JVM process.  We cannot guarantee what will happen otherwise". (ref: https://github.com/mackerelio/mackerel-agent-plugins/tree/master/mackerel-plugin-jvm#user-to-execute-this-plugin ).
That means, in `mackerel-agent.conf`,
```toml
[plugin.metrics.jvm]
command = "mackerel-plugin-jvm -javaname=Bootstrap"
user = "<RUNNER>"
```
Will work well, I expect.

**Comment by azusa** [comment]
@astj 

I add  `user = "<RUNNER>"` to a`mackerel-agent.conf` and restart mackerel-agent, then look a error `/var/log/mackerel-agent.log`.

```
019/09/25 10:49:02 saveValues:  open /var/tmp/mackerel-agent/mackerel-plugin-jvm-721e503a04c275cb20132ae5001c91cabd50f18b: permission denied\n"
```

Then I changed a owner ` /var/tmp/mackerel-agent/mackerel-plugin-jvm*` , then got a appropriate metric on web dashboard successfully.

```
sudo chown <app-user>:<app-group> /var/tmp/mackerel-agent/mackerel-plugin-jvm*
```

Thanks a lot for your support for issue!

**Comment by astj** [comment]
I'm very happy to hear you succeeded!  Feel free to ask us if you have further questions / problems!
