### ISSUE TITLE
[jvm] The PerfDisableSharedMem option

### ISSUE THREAD

**Issue by supercaracal** [mackerelio/mackerel-agent-plugins#568]
Hi,

I am writing to share trouble information related to [Mackerel JVM plugin](https://github.com/mackerelio/mackerel-agent-plugins/tree/master/mackerel-plugin-jvm).

We cannot use the plugin when we use the latest Apache Solr 8.2.0 (2019-09). This is related the following reports.

* [a Hatena Bookmark comment](https://b.hatena.ne.jp/entry/245719266/comment/tmatsuu) (Japanese)
* [JVM statistics cause garbage collection pauses](https://www.evanjones.ca/jvm-mmap-pause.html)
* [hsperfdata causing long GC/safepoint times: Don't use mmap?](http://mail.openjdk.java.net/pipermail/hotspot-runtime-dev/2015-March/014298.html)
* [Cassandra - JVM Tooling](http://cassandra.apache.org/doc/latest/troubleshooting/use_tools.html#jvm-tooling)
* [Why Java performance utilities like jps no longer work in DSE 5.0+](https://support.datastax.com/hc/en-us/articles/360001178023-FAQ-Why-Java-performance-utilities-like-jps-no-longer-work-in-DSE-5-0-)
* [Solr wiki > ShawnHeisey > GC Tuning for Solr > G1 (Garbage First) Collector > Current Experiments](https://cwiki.apache.org/confluence/display/solr/ShawnHeisey#ShawnHeisey-Currentexperiments)
* https://github.com/rhuss/jolokia/issues/198

The Solr is specifing the JVM option `-XX:+PerfDisableSharedMem` as default at the follow.

https://github.com/apache/lucene-solr/blob/e45e8127d5c17af4e4b87a0a4eaf0afaf4f9ff4b/solr/bin/solr#L2027

I can't make up my mind which enable or disable the JVM option yet.

* `-XX:+PerfDisableSharedMem`
* `-XX:-PerfDisableSharedMem`

Maybe we will plan to use alternative plugin. (e.g. [mackerel-plugin-solrjvm](https://github.com/supercaracal/mackerel-plugin-solrjvm))

I'd say that middlewares running on JVM and using `-XX:+PerfDisableSharedMem` option might will be increase.

P.S. I will close this issue later.

**Comment by astj** [comment]
Thank you for detailed information!  We haven't recognized such problems.
Maybe we should mention such cases in README, at least.
