### ISSUE TITLE
[accesslog] Handle multiple values in apptime

### ISSUE THREAD

**Issue by itchyny** [mackerelio/mackerel-agent-plugins#604]
When using the log format `apptime:$upstream_response_time`, the response tiem 
can be multiple values on retry. This results in failure to parse the log line. Maybe only the last value should be used (or summation?).

`ltsv: cannot unmarshal number 0.000, 2.900 into Go value of type float64\n2020/03/24 12:00:00 failed to parse ltsvl`

> Times of several responses are separated by commas and colons like addresses in the $upstream_addr variable.
http://nginx.org/en/docs/http/ngx_http_upstream_module.html

**Comment by susisu** [comment]
Thank you for reporting, @itchyny.
This error is raised by https://github.com/Songmu/axslogparser which is used by mackerel-plugin-accesslog, and I opened an issue there https://github.com/Songmu/axslogparser/issues/19.
mackerel-plugin-accesslog should not fail with such logs, so we will investigate the problem more and  fix it as soon as possible.

**Comment by lufia** [comment]
axslogparse was updated on #615
