### ISSUE TITLE
[mysql] cannot collect metrics after upgrading v0.64.1

### ISSUE THREAD

**Issue by susisu** [mackerelio/mackerel-agent-plugins#769]
We are receiving reports that, after upgrading to v0.64.1, mackerel-plugin-mysql cannot collect metrics and outputs the following log.

```
saveValues: json: unsupported value: +Inf
```

We are now investigating the problem.
If you encountered this issue, please downgrade to v0.64.0 until we release a fixed version.

**Comment by lufia** [comment]
ref golang/go#46628

**Comment by susisu** [comment]
Fixed in [v0.64.2](https://github.com/mackerelio/mackerel-agent-plugins/releases/tag/v0.64.2)
